src/app/components/accountRow/index.tsx

Whenever Stacks or Bitcoin address is copied it shows Copied tooltip text. That text never gets reset. This aims to reset the text back to it's default value after a timeout
When Stacks or Bitcoin address is copied it's tooltip shows Copied indefinitely
As commonly observed across other applications where text gets reset, similarly reset the `Copied` text back to default value after 3 seconds

fix: reset Copied text back to default value after a timeout

---

src/app/screens/ordinalDetail/index.tsx
src/app/screens/restoreFunds/restoreOrdinals/oridnalRow.tsx

when viewing and ordinal and exiting the details page without pressing the back button (clicking the bottom bar) the selected ordinal was being persisted in the store
as a result the wrong ordinals details was shown on the confirm tx screen for ordinal recovery
- selected ordinal gets cleared whenever the details screen gets unmounted
- the correct ordinal details is being set before confirming a recovery

restore-ordinal-showing-wrong-ordinal

---

src/app/components/guards/session.tsx
src/app/hooks/useWalletReducer.ts

If you click on the menu and on "Lock", the popup will show as locked, but if you hide the popup and show it again, it will come up as unlocked.
On lock, the wallet will lock, regardless of whether you hide and show the popup or not.
Before fix:
https://github.com/secretkeylabs/xverse-web-extension/assets/3322667/aa5b6684-c34c-4b54-a3ab-cc6109c710f7

fix: manual lock not locking on popup show and hide

---

src/app/hooks/queries/useBtcWalletData.ts
src/app/hooks/queries/useStxWalletData.ts
src/app/hooks/useWalletReducer.ts

When we are creating a new wallet, we don't have a wallet in the store, but the calls for Stacks and Bitcoin wallet data are firing off with an empty address and there is a constant retry in dev tools resulting in endless 404s.
We only make those calls if there is a bitcoin/stacks wallet address in the store.

fix: don't fire bitcoin and stacks wallet queries when no address

---

src/app/components/checkBox/index.tsx
src/app/screens/backupWallet/index.tsx
src/app/screens/backupWalletSteps/index.tsx
src/app/screens/createPassword/index.tsx
src/app/screens/legalLinks/index.tsx
src/app/screens/onboarding/index.tsx
src/app/screens/restoreWallet/index.tsx
src/app/screens/walletExists/index.tsx

Navigating back during onboarding could cause potential issues, especially after a wallet has been created. Also, navigating to pages that regenerate a seed phrase could result in confusion for the user.
Navigation during onboarding is done with window.replace so that the users cannot navigate backward.

fix: remove back/forward capabilities form onboarding

---

src/app/screens/backupWalletSteps/index.tsx

When creating a new wallet and you went through the "Backup Wallet" flow, if your password and confirmed password don't match, we don't display the error message as it's wrapped in a try catch instead of in the else.
If the passwords don't match, we show the error message

fix: fix the confirm password logic

---

src/app/hooks/useOnTabClosed.ts

Fixes a reference error for deregistering a listener
(Optional) Resolved: 
I'm not sure how this will affect the app but we are deregistering a listener that we didn't register in the first place. It could result in a listener lingering in the background and resources not being closed as expected, but I have the feeling users won't really notice it.
We deregister the tab close listener correctly.

fix: fixes deregister listener bug

---

.github/PULL_REQUEST_TEMPLATE.md

Context Link (if applicable): https://discord.com/channels/895889501560377364/938114005178916945/1116750424486187038
Impact:

Update PR description template

---

package-lock.json
src/app/components/extendedScreenContainer/index.tsx
src/app/components/receiveCardComponent/index.tsx
src/app/components/screenContainer/index.tsx
src/app/components/showBtcReceiveAlert/index.tsx
src/app/components/showOrdinalReceiveAlert/index.tsx
src/app/screens/home/index.tsx
src/app/screens/nftDashboard/index.tsx
src/app/screens/nftDashboard/receiveNft/index.tsx
src/app/screens/receive/index.tsx
src/app/stores/wallet/reducer.ts

The receive alert for bitcoin and ordinal address should show up when user copies the bitcoin and ordinal address. The option to copy the address is in Home screen, Nft Dashboard screen and Receive screen. So the alert should only be shown in these screens.m 
Currently the receive alert for bitcoin and ordinal show up in every screen of the extension. Also if the user is shown the alert and before closing the alert, the extension closes then on reopening the extension, the alert gets shown on the login screen which should not be the case
Issue Link: [#[ENG-2248]](https://linear.app/xverseapp/issue/ENG-2248/receive-address-alert-showing-in-other-open-tabs)
Previously the ordinal and BTC alert dialog was added in the global container screens …

Show receive alert pop up in specific screens only

---

src/app/components/sendForm/index.tsx
src/app/screens/accountList/index.tsx
src/app/screens/confirmBtcTransaction/index.tsx
src/app/screens/sendBtc/index.tsx
src/app/stores/index.ts
src/app/stores/wallet/actions/actionCreators.ts
src/app/stores/wallet/actions/types.ts
src/app/stores/wallet/reducer.ts

Ledger Send BTC flow opens in a separate tab
If user opens popup and switches account, while tab is open, we want to reset the user flow for sending BTC
Issue Link: https://linear.app/xverseapp/issue/ENG-2325/account-switching-mid-ledger-send-flow
- turn state sync on between tabs for the redux action: SelectAccount and SetShouldResetUserFlow
- listen to shouldResetUserFlow flag and reset the send-btc flow (for ledger) when user switches account

Tim/ledger UI fixes

---

src/app/screens/ordinalDetail/index.tsx
src/app/screens/ordinals/brc20Tile.tsx
src/app/screens/ordinals/index.tsx
src/app/screens/ordinals/ordinalImage.tsx
src/locales/en.json

Currently, we don't display HTML ordinals due to security risks, and SVG recursive ordinals don't work in the extension.
We want to display a thumbnail jpg preview of such ordinals.
Issue Link: [ENG-2296](https://linear.app/xverseapp/issue/ENG-2296/display-the-preview-of-a-recursive-ordinal)
- HTML and recursive SVG ordinals are displayed as a thumbnail in the form of a JPG created by the new ordinal viewer service.
- Some styling was fixed in the ordinal gallery within the popup and the gallery view, so BRC-20 token images are now centered regardless of where you are viewing them, and images scale while keeping their aspect ratio of 1:1
- Fixed styling of HTML ordinals
- Changed external ordinal view link to point to our ordinal viewer page …

feat: use ordinal thumbnails (ENG-2296)

---

src/app/components/confirmBtcTransactionComponent/inputOutputComponent.tsx
src/app/screens/signatureRequest/collapsableContainer.tsx

Fixes minor UI issues in the signPsbt screen and sign message screen
In the sign message scree, if the hash is long then string is truncated properly so that the last character is not spilled into the second line.
In the signPsbt Screen BTC unit is also added for inputs now
Issue Link: [#[ENG-2242]](https://linear.app/xverseapp/issue/ENG-2242/transaction-confirmation-input-not-showing-unit-btc)
[#[ENG-2243]](https://linear.app/xverseapp/issue/ENG-2243/message-signing-ui-issue)
Minor change to fix ui in confirmBtcTransactionComponent and SignatureRequest screen

Fix minor confirmation screen ui issues

---

src/app/screens/confirmBtcTransaction/index.tsx
src/app/screens/confirmInscriptionRequest/index.tsx
src/app/screens/confirmOrdinalTransaction/index.tsx
src/app/screens/ledger/confirmLedgerTransaction/index.tsx

Allows multiple btc and ordinal recipients.
Core changes: https://github.com/secretkeylabs/xverse-core/pull/165
Issue Link: [#[issue_number]](https://linear.app/xverseapp/issue/ENG-2270/allow-multiple-recipients-in-ledger-btc-flow)
Changes type of recipient to array. 
All the ledger transactions , BTC (single and multiple recipients), ordinals and BRC20 transfers need to be tested to ensure that everything works as expected

Allow multiple recipients in Ledger BTC flow

---

src/app/screens/confirmFtTransaction/index.tsx
src/app/screens/confirmNftTransaction/index.tsx
src/app/screens/confirmStxTransaction/index.tsx
src/app/screens/sendFt/index.tsx
src/app/screens/sendNft/index.tsx
src/app/screens/sendStx/index.tsx
src/app/screens/transactionRequest/index.tsx

Fix for errors thrown by parsing errors while passing transactions  between the `send-stx` screen and the `confirm-stx-tx` / `confirm-ft-tx` screens
failure to navigate to the stx confirm screens without visual response on what went wrong
Issue Link: https://linear.app/xverseapp/issue/ENG-2410/cant-send-stx-and-sip-10-tokens
stx transactions are serialized then deserialized when being passed as navigation params
Impact:

serialize stx transactions navigation params

---

src/app/screens/swap/swapConfirmation/routeBlock/index.tsx
src/locales/en.json

Remove the text: "For the transaction to proceed, your BTC …"
- remove static text from within the Route section on swap confirmation screen
Impact:
- just the swap confirmation screen

fix: remove static text describing swap route

---

src/app/screens/ledger/importLedgerAccount/index.tsx
src/locales/en.json

The Ledger Live warning screen added as part of this PR does not have the text added to the localization files:
https://github.com/secretkeylabs/xverse-web-extension/pull/527
Issue Link: https://linear.app/xverseapp/issue/ENG-2484/add-localization-for-onboarding-flow-ledger-live-warning-screen
- Added text from Ledger Live warning screen to the localization files
- Changed the width of the options to "100%" to make them wider (as on the design https://www.figma.com/file/FCk8jDMsC8UEfPSWnqewLY/Xverse-%E2%80%94-Extension-V2?node-id=7068%3A173661&mode=dev)

Add localization for onboarding flow Ledger Live warning screen

---

src/app/screens/confirmInscriptionRequest/index.tsx

We show the fiat amount for all line items in the BRC-20 transfer confirmation screen but not the inscription service fee.
changes: 
- show the inscription service fee amount converted to fiat rate
Impact:
- only a UI change on confirm brc20 send screen

feat: show inscription service fee fiat amount

---

package-lock.json
package.json

Bump xverse core version to fix the following:
- Support implicitly setting tapInternalKey for psbt taproot input in https://github.com/secretkeylabs/xverse-core/pull/174
- feat: add the getSponsorInfo function to call /info endpoint in https://github.com/secretkeylabs/xverse-core/pull/173
- fix(bignumber): this will solve the type issues on extension repo in https://github.com/secretkeylabs/xverse-core/pull/109
- fix: Add the sponsored param back to stx transaction type in https://github.com/secretkeylabs/xverse-core/pull/180
Same as above

Bump xverse-core to v1.4.2

---

src/app/screens/home/index.tsx

Issue Link: https://linear.app/xverseapp/issue/ENG-2508/disable-swaps-for-ledger-accounts
- add logic to show/hide the Swap button depending on selected account being ledger or not
Impact:
- only on home screen, show/hide of the Swap button
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/81c0e0cb-4dd4-48dc-8b19-187a9c770ae6

fix: only show swaps button if not on a ledger account

---

src/app/screens/swap/swapConfirmation/stxInfoBlock/index.tsx
src/locales/en.json

see linear bot
Issue: https://linear.app/xverseapp/issue/ENG-2509/swap-confirmation-post-condition-address-tofrom-issue
- added a to/from logic depending on the info block
Impact:
- only on swap confirm screen UI

fix: swap confirm info should display to/from depending on the direction

---

src/app/hooks/useSendBtcRequest.ts

With the current implementation, we currently get the error `Argument of type 'bigint' is not assignable to parameter of type 'Value'`
Noticed this while testing https://github.com/secretkeylabs/sats-connect/pull/25
Impact:

Use toString to convert value to BigNumber

---

src/app/components/button/index.tsx
src/app/screens/swap/index.tsx
src/app/screens/swap/useSwap.tsx

Issue Link: https://linear.app/xverseapp/issue/ENG-2525/swap-continue-button-needs-disableprogress-indicator-when-clicked
- fix: button should always be disabled when processing
- fix: show processing button state in swap by using await, and fix typing
Impact:
- all standard buttons are updated to be disabled if in processing state
- swap screen after clicking continue button
recording created using chrome devtools 6x CPU throttling and slow 3G network throttling
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/e9150bc3-cd64-4965-a2c3-516d9cbe8222

fix: button should always be disabled when processing

---

src/app/screens/ledger/confirmLedgerTransaction/index.tsx
src/app/screens/ledger/verifyLedgerAccountAddress/index.tsx
src/locales/en.json

When you try to verify address and have the wrong device connected, the address screen flashes for a second before showing an error.
We should also display a more useful message that the device is incorrect rather than connection failed.
Issue Link: #[[ENG-2507](https://linear.app/xverseapp/issue/ENG-2507/address-verification-screen-flashes-when-using-wrong-device)]
- Fixed the case when address verification screen flashes when using wrong device
- Added the same error regarding the wrong device usage that we have for other flows like BTC sending, etc.
Impact:
- It impacts the address verification flow for ledger accounts
https://github.com/secretkeylabs/xverse-web-extension/assets/36603049/139b90c3-e2c2-4f43-a431-3bd3bf1139df
Please ensure the following are …

Fix the case when address verification screen flashes when using wrong device

---

package-lock.json
package.json

https://github.com/secretkeylabs/xverse-core/pull/197
support outputscript https://github.com/secretkeylabs/xverse-core/pull/194
add xord and fallback to hiro when required https://github.com/secretkeylabs/xverse-core/pull/187
get Tx by tx_id https://github.com/secretkeylabs/xverse-core/pull/189
fix valid brc20 transfer logic https://github.com/secretkeylabs/xverse-core/pull/193
fix linting issue and enable ci https://github.com/secretkeylabs/xverse-core/pull/176

chore: bump xverse-core to 1.5.0

---

package-lock.json
package.json
src/app/hooks/useSponsoredTransaction.ts
src/app/screens/swap/error.ts
src/app/screens/swap/swapConfirmation/index.tsx
src/app/screens/swap/swapConfirmation/useConfirmSwap.tsx
src/app/screens/swap/swapInfoBlock/index.tsx
src/app/screens/swap/useAlexSponsoredTransaction.ts
src/app/screens/swap/useSwap.tsx
src/app/screens/transactionStatus/index.tsx
src/app/utils/constants.ts

Use Alex sponsor service for swap transactions 
Issue Link: #[[ENG-2548](https://linear.app/xverseapp/issue/ENG-2548/integrate-with-alexs-new-broadcastsponsoredtx-function-and-healthz)]
- The alex-sdk function broadcastsponsoredtx is used to broadcast sponsor transaction instead of using the api endpoint  `/sponsor` from core. 
- The url to check the status for sponsoring service is updated in the core [PR](https://github.com/secretkeylabs/xverse-core/pull/202) 
- alex-sdk also provides list of known codes returned by the sponsoring service `SponsoredTxErrorCode` . The PR deletes the error.ts file and compares the error code with `SponsoredTxErrorCode` from alex-sdl inorder to show the sponsoring alert prompt in the …

Integrate with ALEX's new broadcastsponsoredtx function and healthz endpoint

---

src/app/screens/swap/swapTokenBlock/index.tsx

Issue Link: https://linear.app/xverseapp/issue/ENG-2570/missing-padding-when-the-digits-are-longer 
- styling on swap screen
Impact:
- swap screen UI only
with update:

fix: swap token number input should not overflow

---

src/app/screens/swap/swapConfirmation/advanceSettings/index.tsx
src/app/screens/swap/swapConfirmation/index.tsx
src/app/screens/swap/swapConfirmation/useConfirmSwap.tsx
src/app/screens/swap/useCurrencyConversion.tsx
src/app/screens/swap/useSwap.tsx

The correct fee value was not being displayed in the fee card of the stacks confirmation screen. 
The fee is not updating according to user's settings. if the user chooses to not use sponsored transaction for swapping then the value is not reflected in the ui neither in the stx transaction object. There was an issue with state update
Issue Link: [#[ENG-2569]](https://linear.app/xverseapp/issue/ENG-2569/fee-is-not-being-updated-on-ui)
-The state management is updated so change of fees is reflected.  `onFeeUpdate` function is added in the `useConfirmSwap` . 
- The `useCurrencyConversion` hook is introduced which separates the function `currencyToToken` to be used in different screens. 
- Instead of showing the `lpFeeAmount` in the fee component, …

Fix swap screen fee update issue

---

src/app/components/transactions/stxTransaction.tsx
src/app/components/transactions/txTransfers.tsx
src/app/screens/coinDashboard/transactionsHistoryList.tsx

The correct transaction history for tokens after swap was not being shown 
Issue Link: #[[ENG-2584](https://linear.app/xverseapp/issue/ENG-2584/token-transaction-history-not-displayed-correctly-after-swap)]
Currently we only go through the `stx_transfers` list. Now for fungible token we iterate over the `ft_transfers` list from the transaction object in the txTransfer component. 
Also uses the txFilter to only show the history of relevant token

Fix swaps tx history

---

package-lock.json
package.json

bump xverse-core to 1.6.0
* Add `deviceAccountIndex` field for `Account` interface by @dhriaznov in https://github.com/secretkeylabs/xverse-core/pull/198
* feat: add logic for getting best UTXO combo for txn by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/195
* feat: implement required calls to inscribe service for BRC20 transfer by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/182
* Ordinal transaction functions by @abdulhaseeb4239 in https://github.com/secretkeylabs/xverse-core/pull/201
* Add utils for displaying Brc20 token transaction history by @Imamah-Zafar in https://github.com/secretkeylabs/xverse-core/pull/185
**Full Changelog**: https://github.com/secretkeylabs/xverse-core/compare/v1.5.1...v1.6.0

chore: bump core version to 1.6.0

---

src/app/components/sendForm/index.tsx
src/app/screens/sendBtc/index.tsx
src/app/screens/sendOrdinal/index.tsx
src/locales/en.json

Remove the restriction on sending to your own address for Bitcoin and Ordinal/BRC-20 transfers. Show a warning that this is sending to yourself instead.
https://twitter.com/hotmonkeydeals/status/1681683889662705664?s=20
- remove error validation for send ordinal or send brc-20 to self address
- add option to change warning message of SendForm component
- add onAddressInputChange hook to SendForm component
- display warning if sending ordinal to self
- display warning if sending btc to self
- display warning if sending brc-20 to self
Impact:
- changed interface of the SendForm component, which is shared across other screens, but the optional props should be backward compatible …

Allow send ordinal to self and display warning instead of error

---

package-lock.json
package.json

chore: use release published to trigger a release-package workflow by @teebszet in https://github.com/secretkeylabs/xverse-core/pull/208
feat: use xord for ordinal detection by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/203
fix internalPublicKey update with default by @m-aboelenein in https://github.com/secretkeylabs/xverse-core/pull/206

chore: bump xverse-core to 1.6.1

---

src/app/components/confirmBtcTransactionComponent/index.tsx
src/app/screens/confirmOrdinalTransaction/index.tsx
src/app/screens/restoreFunds/restoreOrdinals/index.tsx
src/app/screens/restoreFunds/restoreOrdinals/ordinalRow.tsx

NOTE: We need to add the new version of core once the Xord Ordinal UTXO detection PR is merged before this is fully functional
When recovering ordinals, we would sometimes spend other ordinals for the transaction. This was because the confirmation screen would regenerate the signed txn hex if the fee was changed, but it wouldn't use the full list of ordinal UTXOs when doing so.
- Added the ordinal UTXO fetch in the confirm txn component so that we don't spend other ordinals
- Fixed an issue where clicking on `transfer` for an ordinal recovery, all the ordinals on the recover screen would show a loader
Core pr: https://github.com/secretkeylabs/xverse-core/pull/203

fix: Don't use ordinals as inputs when recovering ordinals

---

package-lock.json
package.json
src/app/components/guards/auth.tsx
src/app/components/guards/singleTab.tsx
src/app/components/passwordInput/index.tsx
src/app/components/seedPhraseInput/index.tsx
src/app/components/seedPhraseView/index.tsx
src/app/routes/index.tsx
src/app/screens/backupWalletSteps/index.tsx
src/app/screens/backupWalletSteps/verifySeed.tsx
src/app/screens/restoreWallet/enterSeedphrase.tsx
src/app/screens/restoreWallet/index.tsx
src/app/screens/settings/changePassword/index.tsx
src/locales/en.json
src/theme/global.ts
src/theme/index.ts

Issue Link: https://linear.app/xverseapp/issue/ENG-2604/patch-demonic-vulnerability
- restore wallet screen inputs are 12 or 24 input boxes
- create wallet flow will verify based on guessing 3 correct words
- disable user select and copy on any component displaying the whole seed phrase
- add phosphor icon set according to zeroheight https://zeroheight.com/0683c9fa7/p/66541d-icons/b/095f0e
- fix lint errors on routes/index.ts
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/7ed04fab-cedb-4741-9df0-3bd8cc8e360f
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/d83fd456-9360-4f9c-ac5b-24a20ca65445
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/d2b4a977-284f-4e42-b98d-cecc700130db
Please ensure the …

feat: change restore and backup wallet inputs

---

src/app/screens/swap/useAlexSponsoredTransaction.ts

ALEX's sponsor service tries to broadcast replace by fee transactions and that probably causes an issue on the Stacks API. Creating dead pending transactions which results in user's not being able to use sponsored option for alex swap as it always indicates that there is a transaction pending
Issue Link: #[i[ENG-2589](https://linear.app/xverseapp/issue/ENG-2589/filter-out-dead-pending-transactions)]
To filter out dead pending transactions, we first retrieve the account's current nonce. 
To obtain the account's current nonce, relying solely on pending transactions is insufficient. This is because, in the case of a dead pending sponsor transaction, the user might have initiated other transactions (both pending and …

Filter out dead pending transactions

---

src/app/screens/accountList/index.tsx

Selecting an account from the gallery view resulted in the wallet being opened up in full screen instead of going back to the gallery.
The account selection back button and after a new account is selected goes back to the previous page instead of to home.
https://github.com/secretkeylabs/xverse-web-extension/assets/3322667/eac11589-3ce7-4317-9a03-2f62afd82bb8

fix: account select navigation

---

src/inpage/index.ts

Currently we only inject the default stacks and sats providers into the inpage window object. This clashes with other wallets which also inject it in the same place and integrators cannot force select Xverse when calling stacks/sats connect.
Issue Link: ENG-2732
This adds default Xverse providers in an Xverse namespace object on the window object.

feat: add Xverse namespaced providers

---

src/app/screens/ordinals/brc20Tile.tsx
src/app/screens/ordinals/ordinalImage.tsx

brc-20 inscriptions can be text/plain or applicaiton/json type. We only support text/plain at the moment.
brc-20 coin tickers (names) are also case agnostic but we generate different colour backgrounds if the case is different. 
Issue Link: ENG-2767
The fix makes all tickers of the same type the same colour, regardless of case, but it doesn't change the case of the ticker that was used when displaying the preview. Something to consider is that we could change all to lower/upper case for consistency.
- Added support for application/json BRC-20 inscriptions.
- Made colours consistent between different case BRC-20s.
Before:
After:

fix: allow display of brc-20 if application/json type

---

src/app/components/screenContainer/index.tsx
src/pages/Options/index.css

The styling of the popup views in fullscreen (options) mode makes the popup extend to full height instead of going into overflow mode.
Changed the styling to limit it to 80vh with a minimum height of 600px.

fix: improve full screen popup styling

---

src/app/components/sendForm/index.tsx
src/app/components/smallActionButton/index.tsx
src/app/screens/coinDashboard/coinHeader.tsx
src/app/screens/home/index.tsx
src/app/screens/home/squareButton/index.tsx
src/app/screens/sendBrc20/index.tsx
src/app/screens/sendFt/index.tsx

We have an issue with finding the right token for ledger sending flow as it uses the `name` field which may contain some symbols that are not recognized when matching the coin name from the URL with the coin name in array which results in this:
- Changed the field that we use to find the token from `name` to `ticker`
- Fixed the transition for buttons on the main dashboard
Impact:
- This PR impacts `/send-brc20` and `/send-ft` pages

Use `ticker` field instead of `name` for ft and brc-20 token sending

---

package-lock.json
package.json
src/app/screens/createInscription/index.tsx

App fees were not being sent to the apps in the inscription service requests.
Issue Link: #596 
Impact:
- App fees are now sent through with inscription requests
With 10k app fees:
https://mempool.space/tx/fe304d6f356c13917ab90456beb9aafcf73a12fb23490eaaa2a083e2fcf0e1a6#flow=&vout=0
With no app fees:
https://mempool.space/tx/598f94c6b52007cdd857d70a48034d199960f3c8d95ed5d301d5469ed407724f#flow=&vout=0

fix: send through app fees when inscripting

---

src/app/screens/home/balanceCard/index.tsx
src/app/screens/home/index.tsx

When the wallet is on the home screen, it often refetches balances and we display a loader. It also happens if you click off the popup and back onto it. It is a bit annoying and a lot of users have complained about it.
This changes how we calculate when to show the loader to only show it on the initial page load and not on a refetch.
Before:
https://github.com/secretkeylabs/xverse-web-extension/assets/3322667/33817625-a2fa-4d8c-a2d3-0ea03f112ca0
After:
https://github.com/secretkeylabs/xverse-web-extension/assets/3322667/ef274be2-cf75-418c-8dbd-74e876d1c99e

fix: don't show loader on balance refetch on home screen ENG-2757

---

src/app/screens/legalLinks/index.tsx
src/locales/en.json

We want to make the `Authorize data collection` property turned on by default. And we'd also like to add the description for the data collection on the Legal screen.
Issue Link: #[[ENG-3000](https://linear.app/xverseapp/issue/ENG-3000/make-authorize-data-collection-property-turned-on-by-default)]
Context Link (if applicable): https://secretkeylabs.slack.com/archives/C05QCJM9D1N/p1696433854123279
- Made the `Authorize data collection` property turned on by default on the Legal screen.
- Added the description for that property.
Impact:
- This PR impacts the Legal screen and the mixpanel data tracking logic.

Make `Authorize data collection` property turned on by default

---

src/app/hooks/useDetectOrdinalInSignPsbt.ts

We received a bug report form a market place that their PSBT signing stopped working. They narrowed it down to the bundle call failing with a 400/404 when the app tried to check if there were any inscribed/rare sats in the UTXO and the UTXO didn't exist yet as it was an output of an unpublished txn.
Check for a 404 response from the backend for non-existent UTXOs and ignore it when checking for ordinals in a PSBT signing request UTXO.
To test, run this branch alongside the sats-connect example app. On the sign transaction component, go to the utils file with the createPSBT function and change the txid of the UTXO from the payment address to a random, non-existent tx id (line 71).

feat: allow unpublished UTXOs as inputs to PSBTs

---

src/app/screens/nftDashboard/collectiblesTabs.tsx
src/app/screens/nftDashboard/index.tsx

Issue Link: https://linear.app/xverseapp/issue/ENG-3107/disabling-ordinals-user-should-not-see-them-in-the-collectibles-ui 
- fix: load more button on inscriptions now only loads more inscriptions
- fix: disabling/enabling ordinals hides/shows the inscriptions tab and tab button
- fix: disabling/enabling rare sats hides/shows the rare sats tab and tab button
Impact:
- refactored nftDashboard/index.tsx to further separate fetching logic between tabs
- decoupled the useEffect of a stacks address change from an ordinals address change
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/38bd6b4d-a913-4a76-b153-e81580783856

fix: disabling ordinals user should not see them in the

---

package-lock.json
package.json
src/app/screens/createInscription/index.tsx
src/app/screens/executeBrc20Transaction/index.tsx

When we merged in the seed vault, the Inscription and 1 step BRC-20 pages were not updated with the new typing.
This updates the Core version to that with the correct types and implements the type changes.
The Inscription confirmation and 1 step-BRC-20 pages both now pass through the getSeed method from the seed vault instead of the seed phrase. This was tested by making an inscription in Testnet.

fix: inscriptions and 1 step BRC-20 and seed vault (ENG-3125)

---

package.json
src/app/screens/nftDashboard/collectiblesTabs.tsx

- fix: add logic to not display tab buttons when only one tab should show
- chore: fix up the precommit tsc-files check not parsing the custom theme type

fix: only display tab buttons when more than one tab

---

src/app/components/confirmBtcTransactionComponent/index.tsx
src/app/screens/confirmOrdinalTransaction/index.tsx
src/app/screens/nftDashboard/index.tsx
src/theme/index.ts

- https://linear.app/xverseapp/issue/ENG-3132/missing-tooltip-copied-after-clicking-receive-button-for-ledger
- https://linear.app/xverseapp/issue/ENG-3136/not-displaying-rarity-type-for-ordinals-and-the-id
- fix: a bug with ledger device refetching, when no stx address (was the cause of the missing tooltip bug)
- fix: confirm ordinal tx screen - do not display rarity type and id when unless sending a rare sat
impact:
- removed the refetch useEffects reacting to stxAddress or ordinalsAddress change. tested account switching scenarios without these, including with a gallery view open, and on ledger device. concluded they were unnecessary
copied toolip from ledger without STX address:
send ordinal from gallery view ledger:
send ordinal from extension:
send rare sat from extension:
Please …

fix: collectibles UI bugs

---

src/app/hooks/queries/ordinals/useAddressInscriptionCollections.ts
src/app/hooks/queries/ordinals/useAddressInscriptions.ts
src/app/hooks/queries/ordinals/useAddressRareSats.ts
src/app/hooks/queries/ordinals/useCollectionMarketData.ts
src/app/hooks/queries/useAppConfig.ts
src/app/hooks/queries/useBtcWalletData.ts
src/app/hooks/queries/useCoinRates.ts
src/app/hooks/queries/useFeeMultipliers.ts
src/app/hooks/queries/useStxPendingTxData.ts
src/app/hooks/queries/useStxWalletData.ts
src/app/hooks/queries/useTransactions.ts
src/app/hooks/useTextOrdinalContent.ts
src/app/hooks/useWalletReducer.ts
src/app/utils/query.ts

Issue Link: https://linear.app/xverseapp/issue/ENG-3057/investigate-inscriptions-and-rare-sats-query-cache-and-global-query
- set explicit global react-query cache defaults
- prefer use of `staleTime` instead of `refetchXXX: false`, to reduce number of fetches
Impact:
- queries where previously refetches were disabled, and now are enabled:
/src/app/hooks/queries/ordinals/useAddressInscriptionCollections.ts
/src/app/hooks/queries/ordinals/useAddressInscriptions.ts
/src/app/hooks/queries/ordinals/useAddressRareSats.ts
/src/app/hooks/useTextOrdinalContent.ts
- queries where previously would refetch on every mount and window focus, but have added some staleTime to reduce refetches:
/src/app/hooks/queries/ordinals/useCollectionMarketData.ts
/src/app/hooks/queries/useBtcWalletData.ts …

hotfix: react query cache settings

---

src/app/screens/nftDetail/useNftDetail.ts

We need to open NFT page on gamma instead of the whole collection when opened from NFT detail screen
Issue Link: https://linear.app/xverseapp/issue/ENG-3186/see-detail-button-should-open-in-gamma-for-the-specific-stx-nft-not
- changed the URL to open NFT page on gamma
Impact:
-  NFT detail screen
https://github.com/secretkeylabs/xverse-web-extension/assets/29428363/bfb4790d-8b8c-4b33-b553-8dd2eb45cb2e

fix: open NFT gamma link

---

src/app/App.tsx
src/app/screens/nftCollection/index.tsx
src/app/screens/nftCollection/useNftCollection.ts
src/app/ui-library/snackBar.tsx
src/locales/en.json

We need to avoid navigating to NFT detail screen and show a snackbar saying 'Failed to fetch data' if metadata is not fetch properly.
Issue Link: https://linear.app/xverseapp/issue/ENG-3190/handle-the-state-when-the-meta-data-are-not-available
- added a snackbar component in ui-library
- show snackbar if metadata in null
Impact:
- stacks collection screen
https://github.com/secretkeylabs/xverse-web-extension/assets/29428363/b9a40e5f-b4fd-4591-8679-e268c7f04e1c

fix: show snackbar if NFT metadata is failed to fetch

---

.husky/pre-commit
src/app/components/recipientAddressView/index.tsx
src/app/components/sendForm/index.tsx
src/app/components/tabBar/index.tsx
src/app/components/tokenTile/index.tsx
src/app/components/topRow/index.tsx
src/app/hooks/queries/useBnsName.ts
src/app/layouts/sendLayout.tsx
src/app/routes/index.tsx
src/app/screens/coinDashboard/coinHeader.tsx
src/app/screens/home/index.tsx
src/app/screens/nftDashboard/receiveNft/index.tsx
src/app/screens/nftDetail/useNftDetail.ts
src/app/screens/ordinalDetail/useOrdinalDetail.ts
src/app/screens/rareSatsBundle/index.tsx
src/app/screens/rareSatsDetail/rareSatsDetail.tsx
src/app/screens/sendNft/index.tsx
src/app/screens/sendOrdinal/index.tsx
src/app/screens/settings/index.tsx

https://linear.app/xverseapp/issue/ENG-3188/send-stx-nft-screen-in-fullscreen
- fix: ledger accounts should only open in new tab when not already in full screen
- fix: back button display should rely on back history not ledger account
- feat: revamp the send nfts screen to match send ordinals layout (responsive)
Impact:
- send nft screen and send ordinal were refactored to share the same layout, so can check for layout breakages and functional breakages on both screens (extension and full screen view)
- any flow which can open a new tab while using ledger account, now only opens the new tab if not already in full screen
- any Send button
- any Add Stacks Address button
- recover assets button from settings page
- both send nft and send ordinal screens were previously hiding back button if …

feat: revamp stacks nfts send to screen

---

src/app/components/barLoader/index.tsx
src/app/screens/nftCollection/index.tsx
src/app/screens/nftDashboard/nftImage.tsx
src/assets/img/nftDashboard/ic_nft_diamond.svg

This PR replace the older loading nft for a skeleton and fixes some issues in layout and wrong key prop values
Issue Link: #[ENG-3202](https://linear.app/xverseapp/issue/ENG-3202/some-nft-images-are-still-showing-the-moon-loader-spinner-it-should-be)
- tweak BetterBarLoader component to receive string as width and height in order to user percentages
- fix key prop in nft collection screen
- remove hardcoded placeholder size values and replace error icon with the new one
| BEFORE | AFTER |
| :---: | :---: |
| <video src='https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/a8c35a6e-2af3-4121-bc7f-d23628344436'> | <video src='https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/878c4a16-93ba-4c99-919e-80e9cf1a82d7'> |
Please ensure the following are true …

fix: some nft images are still showing the moon loader spinner it should be

---

src/app/hooks/useWalletReducer.ts
src/app/screens/ordinalDetail/index.tsx
src/app/screens/ordinals/ordinalImage.tsx

issue: https://linear.app/xverseapp/issue/ENG-3213/when-clicking-on-the-inscription-image-in-the-details-view
- fix: remove the preview option from rc-image component in ordinals detail
- fix: height was slightly off on ordinal image in detail screen
- fix: details items in two columns were not centrally aligned
- chore: some eslint warnings and type warnings
Impact:
- can check anywhere an ordinal image is displayed
before:
after:

fix: when clicking on the inscription image in the details view

---

src/app/screens/settings/settingComponent/index.tsx

Unable to enter password while resetting password because of layover to disable rare sats option. 
Issue Link: https://linear.app/xverseapp/issue/ENG-3080/transparent-component-may-block-the-user-wants-to-reset-the-wallet
- removed the zIndex from disabled settings option
Impact:
- settings, reset wallet UI
[Uploading Screen Recording 2023-11-13 at 5.29.53 PM.mov…](https://github.com/secretkeylabs/xverse-web-extension/assets/29428363/aa4c18e1-d0d5-4bb7-bef8-60ff7bfdbbaf)

fix: settings layover

---

src/app/screens/createInscription/CompleteScreen.tsx
src/app/screens/transactionStatus/index.tsx
src/locales/en.json

https://linear.app/xverseapp/issue/ENG-3241/extension-crashes-when-closing-the-broadcast-success-screen-issue-is
https://linear.app/xverseapp/issue/ENG-3207/fix-the-copy-on-screen-after-inscribing
- fix: wrong background color on transaction status screens and inscription complete screens
- fix: wrong navigation routes causing crash from transaction status screen
- fix: bad copy on inscription complete screen
Impact:

fix: extension crashes when closing the broadcast success screen

---

package-lock.json
package.json

- bump sats-connect to [1.1.2](https://github.com/secretkeylabs/sats-connect/releases/tag/v1.1.2)
Impact:
- allow inscribing on testnet

chore: bump sats-connect to 1.1.2

---

src/app/components/collectibleCollectionGridItem/index.tsx
src/app/hooks/queries/useNftDetail.ts
src/app/screens/nftCollection/index.tsx

https://linear.app/xverseapp/issue/ENG-3290/bns-domain-failed-to-fetch-data-snackbar-issue
https://linear.app/xverseapp/issue/ENG-3291/bns-domain-thumbnail-size-when-in-fullscreen
- fix: bns thumbnail image was not showing full size
- fix: bns thumbnail should not be clickable on the bns collection screen
- fix: disable the useDetail fetch for bns items (I think @fedeerbes mentioned this in another PR review)
Impact:
- bns thumbnail
- I checked the loading sizes of other thumbnails and they still look correct
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/4334e7a3-8680-4024-b1fb-dfec35d60fc7

fix: bns image size and disable click on bns item

---

src/app/screens/swap/swapTokenBlock/index.tsx

Switching currency doesn't update the currency symbol in the swap asset drawer.
Issue Link: ENG-2691
Impact:
The currency symbol was previously hardcoded to "USD". 
Before: 
After: …

Replace hardcoded USD with dynamic NumericFormat prefix

---

src/app/hooks/queries/ordinals/useAddressRareSats.ts
src/app/hooks/queries/ordinals/useCollectionMarketData.ts
src/app/hooks/queries/useCoinRates.ts
src/app/hooks/useTextOrdinalContent.ts

https://secretkeylabs.slack.com/archives/C05QCJM9D1N/p1700550855171529
- fix: use correct cache keys where staleTime was introduced, but previously cache keys were too broad
Impact:
- also made sure other changed queries in the same commit have enough params in their query cache keys (it could have resulted in bugs where data was cached between switching testnet/mainnet, but would have been very rare because you the other queries were still caching by id as well)
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/f15a077c-87e1-4e43-aafa-385235eef220

fix: fiat rates not fetching when user changed currency

---

src/app/screens/confirmOrdinalTransaction/index.tsx

quickfix for seeing previously sent ordinals in the send ordinal screen
Impact:
- confirm ordinal screen only after clicking next only

fix: reset selected state after sending an ordinal or rare sat bundle

---

src/app/screens/login/index.tsx
src/app/screens/migrationConfirmation/index.tsx
src/locales/en.json

- remove automatic migration for local storage
- show warning for legacy users to reset their wallet
Versions affected: < 0.11.6
local storage migration was failing for legacy users due to compatibility issues with the new security architecture
Issue Link: #[ENG-3316](https://linear.app/xverseapp/issue/ENG-3316/unable-to-see-seed-phrase-when-migrating-from-very-old-version-to)]
Impact:
- legacy users will need to reset their wallet in-order to complete the migration

Hot/fix - migration for legacy users

---

src/app/screens/btcSendScreen/index.tsx

There was a missing import for BigNumber on the send BTC confirmation page.

Add missing BigNumber import (ENG-3326)

---

src/app/screens/nftDashboard/nft.tsx
src/app/utils/constants.ts
src/app/utils/nfts.ts

https://linear.app/xverseapp/issue/ENG-3308/correctly-detect-bns-collections-on-testnet
- fix: determine if the collection / asset is bns name by matching both mainnet and testnet contracts
Impact:
- nft tab (bns name collection)
- nft collection screen (bns item)
mainnet:
testnet:

fix: correctly parse bns names on testnet

---

src/app/hooks/useDetectOrdinalInSignPsbt.ts
src/app/screens/signBatchPsbtRequest/index.tsx
src/app/screens/signPsbtRequest/index.tsx
src/locales/en.json

- Bugfix
This PR fixes an UI issue where we were mixing all the inputs sat bundles under one bundle. The fix shows a sat bundle for each input with an exotic or inscription and it also removes the bundle size component
Issue Link: #[ENG-3392](https://linear.app/xverseapp/issue/ENG-3392/%5Bsatr-ext-12%5D-see-sent-and-received-rare-sats-in-psbt-signing-tx)
- Change logic in useDetectOrdinalInSignPsbt.ts to have an array of bundles
- Use changes in useDetectOrdinalInSignPsbt.ts to show a sat bundle for each input with an exotic or inscription with the input number as a title in single PSBT and batch PSBT
- Remove bundle size component

fix: show sat bundle for each input with an exotic or inscription

---

src/app/components/rareSatAsset/rareSatAsset.tsx
src/app/screens/signPsbtRequest/bundleItemsComponent.tsx
src/app/screens/signPsbtRequest/index.tsx
src/app/utils/rareSats.ts

remember to revert this when working on sign psbt screen v2
https://linear.app/xverseapp/issue/ENG-3392/[satr-ext-12]-see-sent-and-received-rare-sats-in-psbt-signing-tx#comment-eed4c5cb
- reverted the sign psbt file to not display the new Sat bundle UI
- checked out old copies of UI components
- added back missing functions in utils/rare sats and created a quick conversion function
Impact:
- sign psbt screen only

revert: check out old component and hack to display v2 bundle data

---

package-lock.json
package.json
src/app/components/confirmBtcTransactionComponent/index.tsx
src/app/components/transactionSetting/editFee.tsx
src/app/hooks/queries/useTransactions.ts
src/app/hooks/useBtcClient.ts
src/app/hooks/useNonOrdinalUtxo.ts
src/app/hooks/useOrdinalsByAddress.ts
src/app/hooks/useSendBtcRequest.ts
src/app/screens/confirmInscriptionRequest/index.tsx
src/app/screens/createInscription/index.tsx
src/app/screens/ledger/confirmLedgerTransaction/index.tsx
src/app/screens/restoreFunds/restoreOrdinals/index.tsx
src/app/screens/sendBrc20/index.tsx
src/app/screens/sendBrc20OneStep/index.tsx
src/app/screens/sendBtc/index.tsx
src/app/screens/sendOrdinal/index.tsx
src/app/screens/sendRareSat/index.tsx
src/app/screens/settings/changeNetwork/index.tsx
src/app/screens/signPsbtRequest/index.tsx
src/app/utils/helper.ts

We allow the user to change the base Electrs URL that their wallet uses (defaults to mempool.space/api). This was ignored in a variety of core functions which created their own esplora provider instance without considering this URL.
A change was made in Core to have the esplora provider injected into the functions instead of them making the instance themselves. This change required all calls to those functions to inject the esplora provider in the client code, allowing the custom URL to be used.
This will allow people with a lot of UTXOs in their payment address to change the electrs provider and be able to spend their funds.
The provider is now injected where needed. Before this, changing the URL in settings would still result in the use of …

Inject esplora provider into core functions

---

package-lock.json
package.json
src/app/hooks/useDetectOrdinalInSignPsbt.ts

https://linear.app/xverseapp/issue/ENG-3427
depends on https://github.com/secretkeylabs/xverse-core/pull/317
- fix: handle 404s from the get ordinals in utxo endpoint when detecting for the sign psbt screen
Impact:
- sign psbt screen only
with fix:

[ENG-3427] fix: allow-404-get-utxos-from-psbt

---

src/app/screens/transactionRequest/index.tsx

Issue Link: #[ENG-3456](https://linear.app/xverseapp/issue/ENG-3456/stacks-caching-issue-for-the-nonce-on-the-extension)
Impact:

fix nonce not being set correctly for tx requests

---

src/app/screens/confirmFtTransaction/index.tsx
src/app/screens/confirmNftTransaction/index.tsx
src/app/screens/confirmStxTransaction/index.tsx

UI issue with the fee state when you press confirm. It suddenly flashes to a different number before it gets broadcasted. It doesn’t actually get sent as the wrong number but really concerning for users when it does that.
Issue Link: #[[ENG-3455](https://linear.app/xverseapp/issue/ENG-3455/fix-the-sharp-fee-change-on-tx-confirmation)]
Impact:
Before:
https://github.com/secretkeylabs/xverse-web-extension/assets/36603049/5f7add93-d719-4032-9ae5-d3264 …

[ENG-3455] fix: Fix the sharp fee change on tx confirmation

---

package-lock.json
package.json

fix: cap stx contract call fees

---

src/app/components/confirmBtcTransaction/transactionSummary.tsx
src/app/screens/signPsbtRequest/tempMockDataUtil.ts
src/locales/en.json

We need to add a warning in sign psbt screen if we are spending unconfirmed utxos in inputs
Issue Link: https://github.com/secretkeylabs/xverse-web-extension/pull/728
- show callout if any of the inputs of the transaction has an unconfirmed status
Impact:
- Sign Psbt screen

feat: unconfirmed utxo warning in sign psbt

---

.github/workflows/build-rc.yml
.github/workflows/build.yml
.github/workflows/create-release-pr.yml
.github/workflows/release.yml
scripts/.gitignore
scripts/create-release-pr.sh
scripts/find-tag.sh

https://www.notion.so/xverseapp/Xverse-Web-Extension-Release-Instructions-f850e51a4a9f4eba94b9ad27eb8beca6
automating steps 6-8
https://linear.app/xverseapp/issue/ENG-3325
- required some refactoring of the workflows
- refactor build.yaml to:
- trigger only for PRs not named like a release PR
- create a build-rc.yaml for release PRs to:
- trigger on pull_request events to main & develop named like a release PR
- create the release (moved from create-release-pr.yml) 
- build and upload the release asset (moved from release.yml) 
- refactor release.yaml to:
- trigger on merge of release PR to main
- look for the latest release candidate and create the 'latest' release with the same target_comittish

[ENG-3325] chore: refactor workflows

---

package-lock.json
package.json
webpack/webpack.config.js

- ~Mismatched peer dependencies~
- Human readable named classes for styled-components (in development mode)
Issue Link: ENG-3402
Impact:
Please ensure the following are true before …

ENG-3402 Named classes for styled-components

---

src/app/components/confirmBtcTransaction/itemRow/inscription.tsx
src/app/screens/ordinals/ordinalImage.tsx

- Enhancement
This PR adds the showContentTypeThumbnail prop to ordinal image component to use it psbt screens
Issue Link: #[ENG-3534](https://linear.app/xverseapp/issue/ENG-3534/make-sure-thumbnail-looks-good-for-sats-inscriptions-in-extension-and)
Impact:
- PSBT screens for content type of text/plain
| BEFORE | AFTER |
| :---: | :---: |
| <img src='https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/7770b00f-f56f-48bf-9dbc-1002c0edf032' width="50%" height="100%"> | <img src='https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/e6415acf-f7b8-4c80-a577-7ae982a8930b' width="50%" height="100%"> |

chore: add showContentTypeThumbnail prop to ordinal image component and use it in psbt screens

---

src/app/screens/settings/changeNetwork/index.tsx
src/app/screens/settings/changeNetwork/nodeInput.tsx

- fix: skip server validation of api urls if value didn't change
- and skip reset of form if selecting an already selected network
(testnet/mainnet)
- and don't display the x button for clearing if input is empty
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/bc935e17-7383-4a15-98b9-897d9ea3c53b

[ENG-3567] fix: workaround for hiro api 429s on testnet while changing btc

---

src/app/App.tsx
src/app/screens/speedUpTransaction/index.tsx

- add an error message for when stacks speed up fails to sign and broadcast
- updated the error message to remove the 'microblock' part
- fix styling of error toasts

[END 3565] fix: catch and display failed to broadcast error

---

src/app/components/transactionSetting/editBtcFee.tsx
src/app/components/transactionSetting/feeItem.tsx
src/app/hooks/useBtcFees.ts

Issue Link: #[[ENG-3563](https://linear.app/xverseapp/issue/ENG-3563/btc-fee-infinite-loader-when-sending-ordinals)]
Impact:

[ENG-3563] fix: BTC fee infinite loader when sending ordinals

---

src/app/screens/settings/settingComponent/index.tsx

I noticed that we have too wide a vertical indent between the items and the arrow icon is not vertically centered for each of the items, this UI issue is only present on web-extension, and looks good on mobile. This PR aims to fix this UI issue.
Issue Link: #[[ENG-3572](https://linear.app/xverseapp/issue/ENG-3572/fix-indent-on-the-settings-screen)]
Impact:

Fix indent on the Settings screen

---

src/app/components/confirmBtcTransaction/receiveSection.tsx

- Bugfix
This PR fixes a wrong variable used in validation to show top divider for first asset item in receive in payment section component
Issue Link: #[ENG-3584](https://linear.app/xverseapp/issue/ENG-3584/dont-show-divider-in-receive-in-payment-address-section-when-receiving)
Impact:
- PSBT and batch PSBT screens, receive section of the screen. This can be tested in a PSBT tx where user receives an asset in its payment address, maybe as a change 

fix: wrong variable used in validation to show top divider for first asset item in receive in payment section component

---

src/app/hooks/queries/useBtcCoinsBalance.ts

On a newly restored wallet, brcCoinsList will not be populated. As a such, the previous concurrent API calls will not be aware of owned ordinals which will cause no fiat value to be displayed for brc20 tokens. This PR will revert the concurrent calls to a sequential order, which has a slight speed impact, but will ensure that the fiat value will always be displayed. …

fix: Revert getBrc20Tokens to sequential call

---

src/app/screens/home/index.tsx

- Bugfix
This PR fixes the issue around hiding stx in receive modal when stx token is disabled in token management screen
Issue Link: #[ENG-3658](https://linear.app/xverseapp/issue/ENG-3658/after-toggling-off-stx-address-should-be-available-in-the-receive)
- avoid hiding stx address in receive modal when stx token is disabled 
Impact:
- Receive modal, stx address row
https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/137f2405-f249-465b-aa24-3d386262b0e8

fix: hide stx in receive modal when stx token is disabled in token management screen

---

src/app/hooks/queries/ordinals/useInscription.ts
src/app/screens/ordinalDetail/useOrdinalDetail.ts

This is a quick fix and first step to removing the selected NFT reducer. It ensures that the ordinal detail screen only shows the ordinal that the user selected.
Adds a check to ensure that the prepopulated ordinal data matches the selected ordinal.
To test:
1. Open the gallery page
2. Click on a collection
3. Click on an ordinal within the collection
4. Go back to the home screen from the bottom menu 
5. Go to the gallery view
6. Click on a different ordinal that is not part of a collection
The current prod version would show the first ordinal selected instead of the one you want to view. The new version will show the correct one.

Ensure correct ordinal is shown in ordinal detail view

---

src/app/stores/wallet/reducer.ts

https://linear.app/xverseapp/issue/ENG-3674/balance-issue-in-ledger-account-on-v029-rc-sum-doesnt-match-assets
- reset all balances state in store, when switching accounts
Impact:
before:
after
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/d5f1bdfe-3117-4f84-8981-79abc2f58422

fix: reset balance state between change accounts

---

src/app/components/confirmBtcTransaction/transactionSummary.tsx

When showing a transaction summary, we calculate the total amount transferred as the total inputs from your address - the total outputs from your address - fee. This is potentially incorrect as we are assuming that the user is paying the fee, when they aren't necessarily.
No longer subtract the fee from the total being transferred.
Impact:
- This will affect the total transferred amount in the txn confirmation screen in the psbts' screen.

Remove fee subtraction from the You Will Transfer total - ENG-3699

---

src/app/screens/nftDashboard/rareSatsTabGridItem.tsx
src/app/screens/ordinalDetail/index.tsx
src/locales/en.json

rename Sattributes to Satributes
Issue Link: [ENG_3663](https://linear.app/xverseapp/issue/ENG-3663/correct-copy-satribute-not-sattribute)
Context Link (if applicable): 
Impact:
Need a wallet containing an ordinal with satributes, currently not able to

[ENG-3663] fix: Correct Copy: Satribute not Sattribute

---

src/inpage/index.ts

Currently leather injects stacks provider immutably. This breaks our injection of the stacks and btc providers since we inject them together. We need to inject them one by one.

Inject providers individually
