secretkeylabs/xverse-web-extension

package-lock.json, package.json, src/app/components/passwordInput/index.tsx
Reverts secretkeylabs/xverse-web-extension#415
=> Revert "Improve the password strength check"

package-lock.json, package.json, src/app/screens/restoreFunds/restoreOrdinals/index.tsx, src/app/screens/restoreFunds/restoreOrdinals/oridnalRow.tsx
(Optional) Resolved: #425 
Fixes crash when you click on `Recover Ordinals` Tile
Also shows error message incase the transaction is not successfully generated
https://github.com/secretkeylabs/xverse-web-extension/assets/88320460/060add29-277d-4dba-83e6-4a901481ae28
=> Fix crash for recover ordinal

package-lock.json, package.json, src/app/hooks/useSignatureRequest.ts
Message signatures for structured message are not verifiable by apps
fix for structured messages signatures response
=> fix for structured message signing

package.json
Release
(Optional) Resolved: #`Insert issue number`
=> release v0.10.2

src/app/components/confirmBtcTransactionComponent/index.tsx, src/app/components/confirmStxTransactionComponent/index.tsx, src/app/components/transactionSetting/index.tsx
Resolved: #419
Just opening edit fees since there are no other advanced settings
https://github.com/secretkeylabs/xverse-web-extension/assets/36603049/a06ddb70-3fc6-4951-99b0-840f5b7dd6bb
=> Open the Edit fees popup straight away for BTC txs

package-lock.json, package.json
=> release v0.11.0

src/app/components/tokenTile/index.tsx, src/app/hooks/queries/useStxWalletData.ts, src/app/screens/ordinals/brc20Tile.tsx
(Optional) Resolved: #440 
Alignment Issue: 
Fixes stx balance not updating correctly 
https://github.com/secretkeylabs/xverse-web-extension/assets/88320460/bffbd12a-2eb8-428b-9951-98f834c984a9
Also fixes alignment issue
=> Fix ui alignment issue & Stx balance not updating

src/app/components/transactionDetailComponent/index.tsx, src/app/components/transactionsRequests/ContractCallRequest.tsx
https://linear.app/xverseapp/issue/ENG-2194/minor-tx-confirmation-popup-ui-issue
Fixes the minor UI bugs in contract call transaction confirmation screen
=> Fix spacing and alignment issue in Contract call Transaction screen

src/app/screens/ordinalDetail/index.tsx, src/app/screens/ordinals/brc20Tile.tsx
Crash for some users when they go to collectibles screen. 
Some BRC20 token content string have invalid quotation mark which causes the JSON to throw an error when it attempts to parse the string. 
Issue for reference : https://linear.app/xverseapp/issue/ENG-2185/extension-crashes-for-a-user-not-reproducible-for-now
The string is checked to remove the invalid characters and then parsed. 
Also added error handling in case JSON fails to parse an error, we show the collectible placeholder image rather than the extension crashing.
https://github.com/secretkeylabs/xverse-web-extension/assets/88320460/73016e91-b82c-4245-b1da-d24c8232f698
=> Fix ordinal dashboard crash

src/app/screens/ordinalDetail/index.tsx
crash on send ordinal
resolved
=> remove clearing selected ordinal

package-lock.json, package.json
=> release v0.11.2

package-lock.json, package.json
=> release v0.11.3

src/app/hooks/useWalletReducer.ts, src/app/stores/index.ts
=> Bug fix/refactor wallet state

package-lock.json, package.json
=> Release v0.11.4

src/app/hooks/useTextOrdinalContent.ts
(Optional) Resolved: #`Insert issue number`
=> Fix ordinals recovery

src/app/hooks/useWalletReducer.ts
=> hot-fix/disable-cache-migration-for-new-users

package-lock.json, package.json
=> Release v0.11.5

package-lock.json, package.json
Release
(Optional) Resolved: #`Insert issue number`
=> release v0.11.6

src/app/screens/signPsbtRequest/index.tsx
Resolved:[ ENG-2227](https://linear.app/xverseapp/issue/ENG-2227/magic-eden-psbt-signing-testnet-issue)
addresses should show up fine in sign PSBT screen on testnet
=> Fix network in psbt parsing

src/app/screens/restoreFunds/index.tsx
Temporarily disable the BTC recovery from Ordinals address feature due to various indexing issues.
=> Temporarily disable BTC recovery

src/app/screens/transactionRequest/index.tsx
Extension crashes if there is a missing function argument in the contract call transaction request
You get navigated to the error screen indicating that there are missing function arguments.
Run test app https://github.com/secretkeylabs/test-app and remove this line of code https://github.com/secretkeylabs/test-app/blob/01270183f961006fd4fee193801a293562e3c79b/src/dashboard.js#L170
Trigger the extension by clicking on the `Call contract` button
=> Fix crash when stacks function call is missing arguments

package.json
=> Release v0.12.3

package-lock.json, package.json, src/app/components/confirmBtcTransactionComponent/index.tsx, src/app/hooks/useOrdinalsByAddress.ts, src/app/screens/restoreFunds/restoreOrdinals/index.tsx, src/app/screens/restoreFunds/restoreOrdinals/oridnalRow.tsx, src/app/screens/sendOrdinal/index.tsx
https://github.com/secretkeylabs/xverse-core/pull/159
=>  Recover ordinal flow UTXO selection fix

src/app/components/tabBar/index.tsx, src/app/screens/sendBtc/index.tsx, src/app/utils/helper.ts
and hide send btc back button (when loaded in options for ledger)
* 
Impact:
=> feat: ENG-2326 always hide tab bar when in options.html

src/app/screens/swap/swapConfirmation/freesBlock/index.tsx, src/app/screens/swap/swapConfirmation/index.tsx
=> Tim/eng 2307 implement UI fixes from quentins feedback

package-lock.json, package.json
Update xverse core version to latest version
Impact:
=> Update xverse core version

src/app/screens/nftDashboard/index.tsx
When restoring a wallet with ordinals and getting a prompt to activate display of ordinals, pressing activate does not actually activate display until switching to a different tab and coming back.
Issue Link: [#[2388]](https://linear.app/xverseapp/issue/ENG-2388/activate-ordinals-display-issue)
Update the dependency array for NftListView 
https://github.com/secretkeylabs/xverse-web-extension/assets/88320460/c63570ed-ca34-4a51-822f-b2973f45c6ad
=> Fix ordinals display issue

package.json
=> Release v0.13.0

package-lock.json, src/app/screens/ledger/importLedgerAccount/index.tsx, src/app/screens/settings/settingComponent/index.tsx, src/locales/en.json
Issue Link: https://linear.app/xverseapp/issue/ENG-2483/add-before-getting-started-screen-for-ledger-onboarding
Impact:
=> Add Before Getting Started screen for Ledger onboarding

src/app/components/ledger/ledgerInput/index.tsx
Issue Link: https://linear.app/xverseapp/issue/ENG-2486/fix-ledger-account-name-ui-issue
Impact:
=> Fix ledger account name UI issue

src/app/hooks/useResetUserFlow.ts, src/app/screens/accountList/index.tsx, src/app/screens/nftDashboard/index.tsx, src/app/screens/nftDashboard/receiveNft/index.tsx, src/app/screens/sendBrc20/brc20TransferInfo.tsx, src/app/screens/sendBrc20/index.tsx
There is a number of issues found after regression for the v0.14.0-rc.1 version
Issue Link: https://linear.app/xverseapp/issue/ENG-2473/regression-issues-v0140-rc1
- Fixed "Verify addresses" popup width for ledger accounts on the full screen gallery view
- Fixed "NUMBER OF COLLECTIBLES" after activation on the gallery tab in extension view (it showed 0 even after fetching the items)
- Fixed screen crash when changing account on /send-brc20 screen
=> Fix regression issues v0.14.0-rc.1

package-lock.json, src/app/hooks/useSponsoredTransaction.ts, src/app/screens/swap/error.ts, src/app/screens/swap/swapConfirmation/index.tsx, src/app/screens/swap/swapConfirmation/useConfirmSwap.tsx, src/app/screens/swap/swapInfoBlock/index.tsx, src/app/screens/swap/useSwap.tsx, src/app/screens/transactionStatus/index.tsx, src/locales/en.json
All ALEX swaps transactions currently get broadcasted to the stacks-transaction-sponsor service via the react hook
In the case that the sponsor service is active, but returns an error that we know is coming from the sponsor service, we want to offer feedback to the user to try again, but without attempting to use the sponsor service.
Issue Link: [#[ENG-2527]](https://linear.app/xverseapp/issue/ENG-2527/add-an-override-switch-for-sponsoring-transaction-in-swap-screen)
The hook `useSponsoredTransaction` has been modified so it accepts a function argument `isSponsorOptionSelected` which is set using the toggle shown under the details option in the swap screen. The `isSponsored` value is set true when the `isServiceRunning` & …
=> Add an override switch for sponsoring transaction in swap screen

src/app/components/button/index.tsx
If the button entered into loading state then the entire screen would flicker. 
Issue Link: #[ENG-2571](https://linear.app/xverseapp/issue/ENG-2571/ui-glitch-on-the-login-screen-not-an-issue-on-prod-0141)
The transition css styling has been removed since this was the code that caused flickering on different screens
https://github.com/secretkeylabs/xverse-web-extension/assets/88320460/230e7a6f-1d13-4bc3-b1a2-ac68bbda0eb3
=> Fix ui glitch on the login screen

src/app/components/transactions/txTransfers.tsx
Correct decimals for some tokens were not being shown
Use the `ftDecimals` function to use correct decimal places
Impact:
=> Use correct decimal places for fungible token

package-lock.json, package.json, src/app/components/button/index.tsx, src/app/components/transactions/stxTransaction.tsx, src/app/components/transactions/txTransfers.tsx, src/app/screens/coinDashboard/transactionsHistoryList.tsx, src/app/screens/swap/error.ts, src/app/screens/swap/swapConfirmation/advanceSettings/index.tsx, src/app/screens/swap/swapConfirmation/index.tsx, src/app/screens/swap/swapConfirmation/useConfirmSwap.tsx, src/app/screens/swap/swapInfoBlock/index.tsx, src/app/screens/swap/swapTokenBlock/index.tsx, src/app/screens/swap/useAlexSponsoredTransaction.ts, src/app/screens/swap/useCurrencyConversion.tsx, src/app/screens/swap/useSwap.tsx, src/app/screens/transactionStatus/index.tsx, src/app/utils/constants.ts, src/locales/en.json
=> Release v0.15.0

package-lock.json, package.json, src/app/hooks/useBtcAddressRequest.ts, src/app/screens/btcSelectAddressScreen/index.tsx
In the latest develop version of sats-connect, we have changed the type name from `AddressPurposes` to `AddressPurpose`. Currently the extension wont work with the updated version of sats connect. 
Issue Link: [#[issue_number]](https://linear.app/xverseapp/issue/ENG-2539/fix-typing-issues-due-to-sats-connect-v050)
The PR updates the type name to be used with sats-connect
=> Use updated type from sats-connect

package-lock.json, package.json
* fix: guard against read properties of undefined errors in stx helper function by @teebszet in https://github.com/secretkeylabs/xverse-core/pull/213
* Support BTC message signing with ledger accounts by @dhriaznov in https://github.com/secretkeylabs/xverse-core/pull/200
* fix: remove array.at usage as not supported in Native by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/215
**Full Changelog**: https://github.com/secretkeylabs/xverse-core/compare/v1.6.1...v1.6.2-rc.1
=> chore: bump xverse-core to 1.6.2

package-lock.json, package.json
- https://github.com/secretkeylabs/xverse-core/pull/220
=> chore: bump to 1.6.3-rc.1

package-lock.json, package.json
https://github.com/secretkeylabs/xverse-web-extension/releases
* chore: bump xverse-core to 1.6.2 by @teebszet in https://github.com/secretkeylabs/xverse-web-extension/pull/574
* fix: Fix incorrect swap transaction fee ticker by @Imamah-Zafar in https://github.com/secretkeylabs/xverse-web-extension/pull/562
* feat: Add ability to remove connected Ledger account by @dhriaznov in https://github.com/secretkeylabs/xverse-web-extension/pull/524
- https://github.com/secretkeylabs/xverse-web-extension/pull/549
- https://github.com/secretkeylabs/xverse-web-extension/pull/575
**Full Changelog**: https://github.com/secretkeylabs/xverse-web-extension/compare/v0.16.0...v0.17.0
=> release: v0.17.0

src/app/screens/landing/index.tsx, src/pages/Popup/index.css, src/theme/index.ts
Issue with scrollbar UI on the onboarding page 
https://github.com/secretkeylabs/xverse-web-extension/assets/88320460/666e3b22-e05a-4828-aebc-5a2c0d451e09
Fixed the scrollbar UI 
https://github.com/secretkeylabs/xverse-web-extension/assets/88320460/57a3c5d8-45a0-432c-b905-b8f68c7addb1
=> Fix scrollbar in landing page

src/locales/en.json
Minor copy change in settings screen for rare sats feature toggle.
- [x ] No unnecessary or debugging code has been added.
=> fix rare sats settings copy

src/app/components/confirmBtcTransactionComponent/index.tsx, src/app/screens/confirmBtcTransaction/index.tsx
Currently, if you try to send btc in a full screen mode and you refresh the page or use the back/forward browser button the screen crashes.
Issue Link: #[[ENG-3001](https://linear.app/xverseapp/issue/ENG-3001/ledger-send-btc-screen-crash-when-going-back-and-forward)]
- Added a temporary fix for the send btc feature on full screen so that it doesn't crash
The fix is setting the `BigNumber` object prototype which is being lost for several properties when the page is reloaded or when you click the back/forward browser button.
Impact:
- This PR impacts the send btc flow.
https://github.com/secretkeylabs/xverse-web-extension/assets/36603049/e255c102-aff4-43bd-96b2-c29ea84789e9
Please ensure the following are true before …
=> Ledger send btc screen crash when going back and forward

.github/workflows/build.yml, .github/workflows/release.yml, package-lock.json, package.json, src/app/components/stepper/index.tsx, src/react-app-env.d.ts
https://linear.app/xverseapp/issue/ENG-3112/dx-turn-on-type-linting-for-web-extension
- enable type check of staged files before commits
- enable eslint check of all files during the CI build
- declare all svg imports as string type
- fix some type errors in components/stepper/index.tsx
=> chore: turn on tsc --noEmit precommit hook

src/app/screens/legalLinks/index.tsx
Latest develop has a ui issue in the legal screen that needs to be fixed, issue is not present on prod
left img is the develop, right is the latest prod.
Issue Link: #[[ENG-3115](https://linear.app/xverseapp/issue/ENG-3115/ui-issue-in-the-legal-screen-only-latest-develop)]
Impact:
- This PR changes the spacings and font size of several elements on the Legal screen to make it look as it does in design
=> [ENG-3115] fix: UI issue in the legal screen

.github/workflows/build.yml, src/app/utils/rareSats.ts
This PR adds the vout to the end of the txid for unknown rarity items
Issue Link: #[ENG-3083](https://linear.app/xverseapp/issue/ENG-3083/we-need-to-add-the-utxo-vout-at-the-end-of-the-id)
- Create an util to add the vout to the end of the txid and use it for labels
https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/f98eda4e-ff21-4707-813b-9b051b7fb99d
=> feat: add vout to the end of the tx id for unknown rarities

src/app/components/sendForm/index.tsx, src/app/screens/ordinalDetail/index.tsx, src/app/screens/restoreFunds/restoreOrdinals/index.tsx, src/app/screens/signatureRequest/index.tsx
Fix minor UI issues from the backlog 
Issue Link: #[[ENG-2632](https://linear.app/xverseapp/issue/ENG-2632/recover-assets-jumpiness-and-conflicting-infos)]
#[[ENG-2694](https://linear.app/xverseapp/issue/ENG-2694/message-signing-screen-ui-issues)]
#[[ENG-2677](https://linear.app/xverseapp/issue/ENG-2677/no-thousandths-separators-for-stx-balance)]
#[[ENG-2631](https://linear.app/xverseapp/issue/ENG-2631/structure-of-infos-in-inscription-details)]
- Issue ENG-2632: Fixed the jumpiness by adding spinner in the recover ordinal screen 
- Issue ENG-2694: Added scrollbar in message signing screen 
- Issue ENG-2677: Use NumericFormat to add thousandths-separators in send form balance data
- Issue ENG-2631: Adjusted spacing around seperator 
**Fix for …
=> Fix minor UI issues

.eslintrc.json, package.json, src/app/components/transactionsRequests/ContractCallRequest.tsx, src/app/hooks/queries/useBtcWalletData.ts, src/app/hooks/queries/usePendingOrdinalTx.ts, src/app/hooks/queries/useStacksCollectibles.ts, src/app/screens/home/coinSelectModal/index.tsx, src/app/screens/home/index.tsx, src/app/screens/nftDashboard/collectiblesTabs.tsx, src/app/screens/nftDashboard/index.tsx, src/app/screens/ordinals/index.tsx, src/app/screens/restoreFunds/restoreOrdinals/ordinalRow.tsx, src/app/screens/sendStx/index.tsx, src/app/screens/settings/changeNetwork/index.tsx, src/app/screens/settings/changeNetwork/networkRow.tsx, src/app/screens/settings/fiatCurrency/currencyRow.tsx, src/app/screens/stacking/startStacking/index.tsx, src/app/screens/transactionRequest/index.tsx, src/app/stores/wallet/actions/actionCreators.ts, src/app/stores/wallet/actions/types.ts, src/app/utils/constants.ts, src/app/utils/currency.ts, src/app/utils/mixpanel.ts
but not all, as some are not exported yet
fyi @dhriaznov @fedeerbes 
- turn on eslint rule for no internal imports from xverse-core
- and fix some of the cases found, but still many more.
impact:
- no functional changes. only to help clean up how we are using xverse-core imports and how we can package xverse-core in the future
=> chore: turn on eslint rule and fix up some core internal imports

package-lock.json, package.json, src/app/hooks/useWalletReducer.ts, src/app/screens/settings/changeNetwork/index.tsx
- fix: change to testnet page was not imported correctly
- chore: bump xverse-core to 2.3.0
Impact:
- fixed a bnsName type error, which could potentially affect stx bns names
=> fix: unable to change the network to testnet on the latest

package-lock.json, package.json, src/app/hooks/queries/ordinals/useAddressInscriptionCollections.ts, src/app/hooks/queries/ordinals/useAddressInscriptions.ts, src/app/hooks/queries/ordinals/useAddressRareSats.ts, src/app/hooks/queries/ordinals/useCollectionMarketData.ts, src/app/hooks/queries/useAppConfig.ts, src/app/hooks/queries/useBtcWalletData.ts, src/app/hooks/queries/useCoinRates.ts, src/app/hooks/queries/useFeeMultipliers.ts, src/app/hooks/queries/useStxPendingTxData.ts, src/app/hooks/queries/useStxWalletData.ts, src/app/hooks/queries/useTransactions.ts, src/app/hooks/useTextOrdinalContent.ts, src/app/hooks/useWalletReducer.ts, src/app/utils/query.ts
=> hotfix: react query cache fix

src/app/screens/nftDetail/index.tsx
We need to fix buttons width in gallery view in nft detail screen
Issue Link: https://linear.app/xverseapp/issue/ENG-3187/layout-of-the-buttons-in-the-full-screen-detail-page
- change the width of button in gallery view according to the design
=> fix: button in gallery view

src/app/components/collectibleDetailTile/index.tsx, src/app/screens/nftDetail/index.tsx
Small UI differences from design
Issue Link: https://linear.app/xverseapp/issue/ENG-3203/detail-screen-fields-are-not-matching-figma
- added some styling changes 
Impact:
- NFT detail screen UI, no impact on any logic
=> fix: NFT detail screen UI

package-lock.json, package.json, src/app/screens/nftDashboard/useNftDashboard.tsx
This PR hooks the items count with the correct values from latest version of core 2.3.2
Issue Link: #[ENG-3222](https://linear.app/xverseapp/issue/ENG-3222/hook-items-count-with-the-correct-numbers-from-api-and-core)
=> feat: hook items count with correct values

src/app/components/optionsDialog/optionsDialog.tsx, src/app/screens/nftDashboard/collectiblesTabs.tsx
impact: 
- top bar three dot menu
- collectibles dashboard
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/aaa4584d-4fc6-4b9f-ae48-ac4c54733da5
=> fix: z index on sticky tabs list and modals, popups

.husky/pre-commit, package-lock.json, package.json, src/app/components/collectibleCollage/collectibleCollage.tsx, src/app/hooks/queries/useNftDetail.ts, src/app/hooks/queries/useStacksCollectibles.ts, src/app/screens/confirmNftTransaction/index.tsx, src/app/screens/nftCollection/index.tsx, src/app/screens/nftCollection/useNftCollection.ts, src/app/screens/nftDashboard/nft.tsx, src/app/screens/nftDashboard/nftImage.tsx, src/app/screens/nftDashboard/nftTabGridItem.tsx, src/app/screens/nftDashboard/useNftDashboard.tsx, src/app/screens/nftDetail/index.tsx, src/app/screens/nftDetail/useNftDetail.ts, src/app/screens/sendNft/index.tsx, src/app/utils/nfts.ts, src/react-app-env.d.ts
issue: https://linear.app/xverseapp/issue/ENG-3257/adapt-extension-to-fetch-nft-details
- refactor: use new stx fetch logic (decouple collections fetch from image+details fetch)
- feat: virtualise the grid on nft dashboard and nft collection screen to load image+details just in time
Impact:
- nfts tab
- nft collection screen
- nft detail screen
- nft send screen
- nft confirm tx screen
https://github.com/secretkeylabs/xverse-web-extension/assets/6109710/5544aeb4-349a-40cb-8f5a-d2740cdd29b1
=> refactor: collectibles fetch

package-lock.json, package.json, src/app/screens/btcSendScreen/index.tsx
Fix issue where extension crashes when processing a BTC payment request. There was a missing import for BigNumber on the send BTC confirmation page.
https://github.com/secretkeylabs/xverse-web-extension/pull/682
=> release: v0.23.2 to develop

package-lock.json, package.json, src/app/components/exoticSatsRow/exoticSatsRow.tsx, src/app/hooks/queries/ordinals/tempAddressRareSatsMock.ts, src/app/hooks/queries/ordinals/useAddressRareSats.ts, src/app/screens/nftDashboard/collectiblesTabs.tsx, src/app/screens/nftDashboard/rareSatsTabGridItem.tsx, src/app/screens/nftDashboard/supportedRarities/index.tsx, src/app/utils/rareSats.ts
This PR updated the version of core to have latest changes related to unsupported types and also fixes logic and ui issues in RareSatsTabGridItem
Issue Link: #[ENG-3362](https://linear.app/xverseapp/issue/ENG-3362/address-unsupported-type-changes-from-core)
| UNSUPPORTED TYPES | MIXED TYPES |
| :---: | :---: |
| <video src='https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/188c10db-1f1f-4466-8bcd-cb01cc000f92' width="50%" height="100%"> | <video src='https://github.com/secretkeylabs/xverse-web-extension/assets/18606335/4e80b85e-6120-40e5-99e1-f1ad50bffd9b' width="50%" height="100%"> |
=> fix: logic and ui in RareSatsTabGridItem component

package-lock.json, package.json, src/app/components/confirmBtcTransactionComponent/index.tsx, src/app/components/rareSatAsset/rareSatAsset.tsx, src/app/components/screenContainer/index.tsx, src/app/hooks/useDetectOrdinalInSignPsbt.ts, src/app/layouts/sendLayout.tsx, src/app/routes/index.tsx, src/app/screens/confirmBtcTransaction/index.tsx, src/app/screens/confirmOrdinalTransaction/index.tsx, src/app/screens/createInscription/ErrorModal/index.tsx, src/app/screens/home/index.tsx, src/app/screens/restoreFunds/restoreOrdinals/index.tsx, src/app/screens/sendBrc20OneStep/brc20TransferForm.tsx, src/app/screens/sendNft/index.tsx, src/app/screens/sendOrdinal/index.tsx, src/app/screens/sendRareSat/index.tsx, src/app/screens/settings/index.tsx, src/app/screens/settings/settingComponent/index.tsx, src/app/screens/signBatchPsbtRequest/index.tsx, src/app/screens/signPsbtRequest/bundleItemsComponent.tsx, src/app/screens/signPsbtRequest/index.tsx, src/app/ui-library/common.styled.ts, src/app/utils/rareSats.ts, src/locales/en.json, src/pages/Options/index.css, src/pages/Popup/index.css, src/pages/Popup/index.html, src/theme/index.ts
* [ENG-3314] feat: support repeat minter by @teebszet in https://github.com/secretkeylabs/xverse-web-extension/pull/687
* release: v0.24.0 to main by @teebszet in https://github.com/secretkeylabs/xverse-web-extension/pull/690
* release: v0.24.0 to develop by @teebszet in https://github.com/secretkeylabs/xverse-web-extension/pull/691
* fix: add copy to create inscription error modal by @teebszet in https://github.com/secretkeylabs/xverse-web-extension/pull/696
* [ENG-3384] fix: UI issues found in 0.24 by @teebszet in https://github.com/secretkeylabs/xverse-web-extension/pull/698
* [ENG-3392] fix: show sat bundle for each input with an exotic or inscription by @fedeerbes in https://github.com/secretkeylabs/xverse-web-extension/pull/701
* [ENG-3392] revert: check out old component and hack …
=> release: v0.25.0 to develop

package-lock.json, package.json
* release: v0.26.0 to develop by @github-actions in https://github.com/secretkeylabs/xverse-web-extension/pull/708
* ENG-3383 Allow copy pasting entire seed phrase for developers only by @jordankzf in https://github.com/secretkeylabs/xverse-web-extension/pull/697
* [ENG-3427] fix: allow-404-get-utxos-from-psbt by @teebszet in https://github.com/secretkeylabs/xverse-web-extension/pull/709
* Fix account referencing issue on login by @victorkirov in https://github.com/secretkeylabs/xverse-web-extension/pull/710
* fix nonce not being set correctly for tx requests by @m-aboelenein in https://github.com/secretkeylabs/xverse-web-extension/pull/716
* [ENG-3455] fix: Fix the sharp fee change on tx confirmation by @dhriaznov in …
=> Release v0.26.1 to develop

.github/workflows/build.yml
=> chore: fix build workflow file

src/app/components/tokenTile/index.tsx, src/app/screens/coinDashboard/coinHeader.tsx
=> ENG-2630: Remove BRC-20 / SIP-10 token labels

package-lock.json, package.json, src/app/screens/coinDashboard/transactionsHistoryList.tsx, src/app/screens/speedUpTransaction/index.tsx, src/app/utils/constants.ts
What kind of change does this PR introduce
refactor RBF props for BTC 
Impact:
- Need to re-test BTC RBF
=> Bug fix/rbf support custom seed handler

.github/workflows/build-rc.yml
=> chore: fix build-rc.yml workflow file

.github/workflows/build-rc.yml, .github/workflows/release.yml
=> chore: fix workflow bugs

scripts/find-tag.sh
=> chore: fix find tag script

src/app/hooks/useRbfTransactionData.ts
Issue Link: #[[ENG-3564](https://linear.app/xverseapp/issue/ENG-3564/speed-up-transaction-ui-issue-displaying-and-loading)]
Impact:
https://github.com/secretkeylabs/xverse-web-extension/assets/36603049/45333964-d199-41b5-abe4-6563903fe6d5
Please ensure the following are true before …
=> [ENG-3564] fix: Speed up transaction ui issue displaying and loading

.github/workflows/release.yml
=> chore: fix publish release workflow target committish

src/app/screens/rareSatsBundle/index.tsx
https://linear.app/xverseapp/issue/ENG-3580/missing-localization-in-dialog-for-sent-pending-rare-sat
- transaltion strings only
=> fix: translation strings

.github/workflows/build-rc.yml
=> chore: fix update description on build-rc workflow

src/app/screens/createPassword/index.tsx
=> bug-fix/confirm-passoword-button

src/app/components/seedPhraseView/index.tsx, src/app/components/seedPhraseView/word.tsx, src/app/screens/backupWalletSteps/verifySeed.tsx
Ensure google translate skips the seed phrase
=> Ensure translations are not applied to seed phrases

src/app/screens/connect/btcSelectAddressScreen/index.tsx
infinite loading issue on the `sats-connect` connection screen for Dapp with no manifest
Impact:
=> bug-fix/app-icon-fetching-failure

src/app/screens/nftDashboard/rareSatsTabGridItem.tsx, src/app/screens/ordinalDetail/index.tsx, src/inpage/index.ts, src/locales/en.json
Ensure we inject the providers.
=> Fix in page provider injection

src/content-scripts/content-script.ts, src/manifest.json
Try and inject the content script as-soon-as the extension is installed
Impact:
=> prioritize content script injection

.github/workflows/release.yml
Issue Link: ENG-3805
- chore: attach zipped build to latest release on merge to main
=> [ENG-3805] chore: attach zipped web extension to latest release

package-lock.json, package.json
- Other... Please describe: core update 
This PR updates the core version to 11.1.1
Issue Link: #[ENG-3817](https://linear.app/xverseapp/issue/ENG-3817/update-the-core-version-in-the-web-extension)
Impact:
- PSBT screen
=> chore: bump core to v11.1.1

src/app/components/confirmBtcTransaction/transactionSummary.tsx
Issue Link: ENG-4466
Context Link (if applicable): https://linear.app/xverseapp/issue/ENG-4466/%F0%9F%A6%8B%E2%9A%A0%EF%B8%8F-user-confused-about-rare-sats-in-payment-address-callout#comment-d6b3873a
Impact: …
=> Hide rare sats warning
